version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: security_postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: dbsecuritytemplate
      POSTGRES_USER: securityuser
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres-security-template-data:/var/lib/postgresql/data
    networks:
      - security-template-network

volumes:
  postgres-security-template-data:

networks:
  security-template-network: