spring:
  application:
    name: security-template

  profiles:
    active: dev

# ===========================
# Configuración de Seguridad
# ===========================
security:
  authorization-mode: groups  # AUTHORITIES o GROUPS

# ===========================
# Configuración JWT
# ===========================
jwt:
  secret:
    key: ${JWT_SECRET:your-very-secure-secret-key-min-256-bits-long-change-this-in-production}
  issuer: ${JWT_ISSUER:Security-Template-App}
  access:
    expiration: ${JWT_ACCESS_EXPIRATION_MS:300000}    # 20 segundos
  refresh:
    expiration: ${JWT_REFRESH_EXPIRATION_MS:604800000} # 7 días