spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/dbsecuritytemplate
    username: securityuser
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always
      schema-locations: classpath:db/security/01-security-schema.sql
      data-locations: classpath:db/security/02-security-data.sql
      continue-on-error: false

logging:
  level:
    org.springframework.security: DEBUG
    com.jonathanmarquez.security: DEBUG
    com.jonathanmarquez.security.security.filter: DEBUG
    com.jonathanmarquez.security.security.utils: DEBUG

server:
  port: 8081